# =========================
# APPLICATION NAME
# =========================
spring.application.name=rcc-lms

# =========================
# DATABASE CONFIG
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=1234

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# =========================
# SERVER PORT
# =========================
server.port=5001

# =========================
# SUPPRESS WARNINGS
# =========================
spring.security.user.name=admin
spring.security.user.password=admin